version: "3.8"

networks:
  default:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  promtail:
    image: grafana/promtail
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yaml
      - /var/log/fastapi:/var/log/fastapi
    command: -config.file=/etc/promtail/config.yaml

  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # RabbitMQ protocol
      - "15672:15672"    # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - default

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    networks:
      - default

  main-service:
    build:
      context: ./main-service
      dockerfile: Dockerfile
    container_name: main-service
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - qdrant
    networks:
      - default

  insertion-service:
    build:
      context: ./insertion-service
      dockerfile: Dockerfile
    container_name: insertion-service
    depends_on:
      - rabbitmq
      - qdrant
    networks:
      - default

  storage-service:
    build:
      context: ./storage-service
      dockerfile: Dockerfile
    container_name: storage-service
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq
      - qdrant
    networks:
      - default
  sync-consumer-service:
    build: 
      context: ./sync-consumer-service
      dockerfile: dockerfile
    container_name: sync-consumer-service

    depends_on:
      - rabbitmq
      - qdrant

volumes:
  rabbitmq_data:

