FROM python:3.9-slim

WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir locust

# Copy the locust file
COPY advanced_locustfile.py .

# Expose the Locust web interface ports
EXPOSE 8089

# Command to run Locust
CMD ["locust", "-f", "advanced_locustfile.py", "--host=http://main-service:8000", "--web-host=0.0.0.0"]
